name: doan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cupertino_icons: ^1.0.2
  # Thêm sau cho UI đẹp hơn (tùy chọn)
  fluttertoast: ^9.0.0  # Hiển thị thông báo
  loading_animation_widget: ^1.2.0+4  # Loading spinner
  image_picker: ^1.2.0
  video_player: ^2.10.0
  firebase_storage: ^13.0.3
  cloud_firestore: ^6.0.3
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  path_provider: ^2.1.3 # Kiểm tra phiên bản mới nhất
  permission_handler: ^12.0.1 # Kiểm tra phiên bản mới nhất
  file_saver: ^0.3.1 # Kiểm tra phiên bản mới nhất
  pdf: ^3.11.3
  printing: ^5.14.2
  http: ^1.5.0
  open_filex: ^4.7.0
  url_launcher: ^6.3.2
  flutter_file_dialog: ^3.0.2
  provider: ^6.1.5+1
  chat_bubbles: ^1.7.0
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.2.15
  timeago: ^3.7.1
  google_sign_in: ^6.2.1
  animate_do: ^4.2.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
